# Midterm project work
### Nicholas Gildenhuys

In [1]:
import geopandas as gpd
import pandas as pd
import sqlalchemy as ql

In [121]:
vaccine_data_file = "Data/COVID-19_Vaccinations_in_the_United_States_County.csv"
vac_by_county = pd.read_csv(vaccine_data_file)
#vac_by_county

C:\Users\NicholasWGildenhuys\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [122]:
us_counties = gpd.read_file('Data/UScounties/UScounties.shp')
#us_counties

In [123]:
combined_df = us_counties.merge(vac_by_county, on='FIPS')
#combined_df

In [124]:
#combined_df.to_csv('US_COVID_Vaccination_by_County.csv')

In [125]:
combined_df.columns

Index(['NAME', 'STATE_NAME', 'STATE_FIPS', 'CNTY_FIPS', 'FIPS', 'geometry',
       'Date', 'MMWR_week', 'Recip_County', 'Recip_State',
       'Series_Complete_Pop_Pct', 'Series_Complete_Yes',
       'Series_Complete_12Plus', 'Series_Complete_12PlusPop_Pct',
       'Series_Complete_18Plus', 'Series_Complete_18PlusPop_Pct',
       'Series_Complete_65Plus', 'Series_Complete_65PlusPop_Pct',
       'Completeness_pct', 'Administered_Dose1_Recip',
       'Administered_Dose1_Pop_Pct', 'Administered_Dose1_Recip_12Plus',
       'Administered_Dose1_Recip_12PlusPop_Pct',
       'Administered_Dose1_Recip_18Plus',
       'Administered_Dose1_Recip_18PlusPop_Pct',
       'Administered_Dose1_Recip_65Plus',
       'Administered_Dose1_Recip_65PlusPop_Pct', 'SVI_CTGY',
       'Series_Complete_Pop_Pct_SVI', 'Series_Complete_12PlusPop_Pct_SVI',
       'Series_Complete_18PlusPop_Pct_SVI',
       'Series_Complete_65PlusPop_Pct_SVI', 'Metro_status',
       'Series_Complete_Pop_Pct_UR_Equity',
       'Series_Complete_12PlusPop_Pct_UR_Equity',
       'Series_Complete_18PlusPop_Pct_UR_Equity',
       'Series_Complete_65PlusPop_Pct_UR_Equity'],
      dtype='object')

In [126]:
unused_data = ['CNTY_FIPS', 'STATE_FIPS', 'Recip_County', 'Recip_State', 'MMWR_week', 'Series_Complete_12Plus', 'Series_Complete_12PlusPop_Pct',
       'Series_Complete_18Plus', 'Series_Complete_18PlusPop_Pct',
       'Series_Complete_65Plus', 'Series_Complete_65PlusPop_Pct',
       'Completeness_pct', 'Administered_Dose1_Recip',
       'Administered_Dose1_Pop_Pct', 'Administered_Dose1_Recip_12Plus',
       'Administered_Dose1_Recip_12PlusPop_Pct',
       'Administered_Dose1_Recip_18Plus',
       'Administered_Dose1_Recip_18PlusPop_Pct',
       'Administered_Dose1_Recip_65Plus',
       'Administered_Dose1_Recip_65PlusPop_Pct', 'SVI_CTGY',
       'Series_Complete_Pop_Pct_SVI', 'Series_Complete_12PlusPop_Pct_SVI',
       'Series_Complete_18PlusPop_Pct_SVI',
       'Series_Complete_65PlusPop_Pct_SVI', 'Metro_status',
       'Series_Complete_Pop_Pct_UR_Equity',
       'Series_Complete_12PlusPop_Pct_UR_Equity',
       'Series_Complete_18PlusPop_Pct_UR_Equity', 'Series_Complete_65PlusPop_Pct_UR_Equity']
trimmed_df = combined_df.drop(labels=unused_data, axis=1)

In [127]:
pop_df = pd.read_csv('Data/population_data.csv')
pop_df['FIPS'] = ((pop_df['STATE'] * 1000) + pop_df['COUNTY'])
pop_df['FIPS'] = pop_df['FIPS'].astype(str)
pop_columns = ['POPESTIMATE2019', 'FIPS']

In [128]:
trimmed_pop_df = pop_df[pop_columns]
pop_df['FIPS']

0        1000
1        1001
2        1003
3        1005
4        1007
        ...
3188    56037
3189    56039
3190    56041
3191    56043
3192    56045
Name: FIPS, Length: 3193, dtype: object

In [129]:
trimmed_df['Date'] = pd.to_datetime(trimmed_df.Date)
#trimmed_df.sort_values('Date')
trimmed_df_with_pop = trimmed_df.merge(trimmed_pop_df, on='FIPS')
#trimmed_df_with_pop['Cacl_p'] = trimmed_df_with_pop['Series_Complete_Yes'] / trimmed_df_with_pop['POPESTIMATE2019']
trimmed_df_with_pop

,NAME,STATE_NAME,FIPS,geometry,Date,Series_Complete_Pop_Pct,Series_Complete_Yes,POPESTIMATE2019,Cacl_p
0,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-09,49.7,1857,3740,0.496524
1,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-08,49.5,1852,3740,0.495187
2,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-07,49.4,1848,3740,0.494118
3,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-06,49.4,1847,3740,0.493850
4,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-05,49.4,1847,3740,0.493850
...,...,...,...,...,...,...,...,...,...
846258,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2020-12-18,0.0,0,40044,0.000000
846259,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2020-12-17,0.0,0,40044,0.000000
846260,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2020-12-16,0.0,0,40044,0.000000
846261,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2020-12-15,0.0,0,40044,0.000000
846262,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2020-12-14,0.0,0,40044,0.000000

In [130]:
#most_recent_report = max(trimmed_df_with_pop.Date)
#most_recent_report

Timestamp('2021-10-09 00:00:00')

In [131]:
demo_df = pd.read_csv('Data/us_county_demographic_data.csv', header=1)
demo_df

,id,Geographic Area Name,!!Total:,!!Total:!!Population of one race:,!!Total:!!Population of one race:!!White alone,!!Total:!!Population of one race:!!Black or African American alone,!!Total:!!Population of one race:!!American Indian and Alaska Native alone,!!Total:!!Population of one race:!!Asian alone,!!Total:!!Population of one race:!!Native Hawaiian and Other Pacific Islander alone,!!Total:!!Population of one race:!!Some Other Race alone,...,!!Total:!!Population of two or more races:!!Population of four races:!!American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,!!Total:!!Population of two or more races:!!Population of five races:,!!Total:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander,!!Total:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Asian; Some Other Race,!!Total:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race,!!Total:!!Population of two or more races:!!Population of five races:!!White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,!!Total:!!Population of two or more races:!!Population of five races:!!White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,!!Total:!!Population of two or more races:!!Population of five races:!!Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race,!!Total:!!Population of two or more races:!!Population of six races:,!!Total:!!Population of two or more races:!!Population of six races:!!White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race
0,0500000US01001,"Autauga County, Alabama",58805,55648,42160,11445,217,881,35,910,...,0,2,2,0,0,0,0,0,0,0
1,0500000US01003,"Baldwin County, Alabama",231767,216743,189399,18217,1582,2067,143,5335,...,0,0,0,0,0,0,0,0,0,0
2,0500000US01005,"Barbour County, Alabama",25223,24523,11317,11933,116,117,1,1039,...,0,2,2,0,0,0,0,0,0,0
3,0500000US01007,"Bibb County, Alabama",22293,21534,16555,4413,60,32,9,465,...,0,0,0,0,0,0,0,0,0,0
4,0500000US01009,"Blount County, Alabama",59134,55478,50663,845,337,178,24,3431,...,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,0500000US72147,"Vieques Municipio, Puerto Rico",8249,6127,1551,1256,86,7,1,3226,...,0,0,0,0,0,0,0,0,0,0
3218,0500000US72149,"Villalba Municipio, Puerto Rico",22093,11151,3429,1380,130,10,0,6202,...,0,0,0,0,0,0,0,0,0,0
3219,0500000US72151,"Yabucoa Municipio, Puerto Rico",30426,19720,5028,2941,199,8,7,11537,...,0,0,0,0,0,0,0,0,0,0
3220,0500000US72153,"Yauco Municipio, Puerto Rico",34172,18958,7312,1617,209,25,2,9793,...,0,0,0,0,0,0,0,0,0,0
3221,0100000US,United States,331449281,297600338,204277273,41104200,3727135,19886049,689966,27915715,...,553,21685,8632,9141,1137,1021,1309,445,2505,2505

In [132]:
demo_df['FIPS'] = demo_df['id'].str[9:]
#demo_df['FIPS'] = demo_df['id']
demo_df.columns
demo_df['Minority_Pct'] = (-1 * (demo_df[' !!Total:!!Population of one race:!!White alone'] / demo_df[' !!Total:'])) + 1
demo_df['Minority_Pct']

0       0.283054
1       0.182804
2       0.551322
3       0.257390
4       0.143251
          ...
3217    0.811977
3218    0.844792
3219    0.834747
3220    0.786024
3221    0.383685
Name: Minority_Pct, Length: 3222, dtype: float64

In [133]:
cols = ['Minority_Pct', 'FIPS']
trimmed_demo_df = demo_df[cols]
trimmed_demo_df

      Minority_Pct   FIPS
0         0.283054  01001
1         0.182804  01003
2         0.551322  01005
3         0.257390  01007
4         0.143251  01009
...            ...    ...
3217      0.811977  72147
3218      0.844792  72149
3219      0.834747  72151
3220      0.786024  72153
3221      0.383685

[3222 rows x 2 columns]

In [134]:
final_df = trimmed_df_with_pop.merge(trimmed_demo_df, on='FIPS')
final_df

,NAME,STATE_NAME,FIPS,geometry,Date,Series_Complete_Pop_Pct,Series_Complete_Yes,POPESTIMATE2019,Cacl_p,Minority_Pct
0,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-09,49.7,1857,3740,0.496524,0.066702
1,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-08,49.5,1852,3740,0.495187,0.066702
2,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-07,49.4,1848,3740,0.494118,0.066702
3,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-06,49.4,1847,3740,0.493850,0.066702
4,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-05,49.4,1847,3740,0.493850,0.066702
...,...,...,...,...,...,...,...,...,...,...
846258,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2020-12-18,0.0,0,40044,0.000000,0.594694
846259,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2020-12-17,0.0,0,40044,0.000000,0.594694
846260,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2020-12-16,0.0,0,40044,0.000000,0.594694
846261,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2020-12-15,0.0,0,40044,0.000000,0.594694
846262,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2020-12-14,0.0,0,40044,0.000000,0.594694

In [135]:
most_recent_report = max(trimmed_df_with_pop.Date)
most_recent_report

Timestamp('2021-10-09 00:00:00')

In [136]:
final_recent_df = final_df[final_df.Date == most_recent_report]
final_recent_df

,NAME,STATE_NAME,FIPS,geometry,Date,Series_Complete_Pop_Pct,Series_Complete_Yes,POPESTIMATE2019,Cacl_p,Minority_Pct
0,Lake of the Woods,Minnesota,27077,"POLYGON ((-95.34283 48.54668, -95.34105 48.715...",2021-10-09,49.7,1857,3740,0.496524,0.066702
300,Ferry,Washington,53019,"POLYGON ((-118.85163 47.94956, -118.84846 48.4...",2021-10-09,48.1,3671,7627,0.481316,0.286988
600,Stevens,Washington,53065,"POLYGON ((-117.43883 48.04412, -117.54219 48.0...",2021-10-09,34.2,15655,45723,0.342388,0.153558
900,Okanogan,Washington,53047,"POLYGON ((-118.97209 47.93915, -118.97406 47.9...",2021-10-09,60.8,25669,42243,0.607651,0.344338
1201,Pend Oreille,Washington,53051,"POLYGON ((-117.43858 48.99992, -117.03205 48.9...",2021-10-09,34.8,4780,13724,0.348295,0.118648
...,...,...,...,...,...,...,...,...,...,...
844765,Honolulu,Hawaii,15003,"POLYGON ((-157.67333 21.29803, -157.68137 21.2...",2021-10-09,0.0,0,974563,0.000000,0.814599
845065,Maui,Hawaii,15009,"MULTIPOLYGON (((-156.19605 20.63165, -156.2763...",2021-10-09,0.0,0,167417,0.000000,0.671006
845364,Hawaii,Hawaii,15001,"POLYGON ((-155.66619 18.92179, -155.77859 19.0...",2021-10-09,0.0,0,201513,0.000000,0.664231
845664,Pittsylvania,Virginia,51143,"POLYGON ((-79.71720 36.54803, -79.64135 36.846...",2021-10-09,38.0,22938,60354,0.380058,0.261632
845963,Danville,Virginia,51590,"POLYGON ((-79.51977 36.59777, -79.50138 36.621...",2021-10-09,33.3,13354,40044,0.333483,0.594694

In [137]:
final_recent_df.to_csv('final_trimmed_data.csv')